# Generated by Django 4.2.7 on 2023-12-09 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_contact_orders'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orders',
            old_name='oder_id',
            new_name='order_id',
        ),
        migrations.AddField(
            model_name='orders',
            name='phone',
            field=models.CharField(default='', max_length=111),
        ),
    ]
